os: osx
language: node_js
env:
  global:
    - ENCRYPTION_LABEL: "4ca5d6902761"
    - COMMIT_AUTHOR_EMAIL: "me+cv_travis_bot@estebantorr.es"
cache:
  directories:
  - node_modules

  before_script: 
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'
  - nvm install 11.1
  - npm install
  
  script:
  - make deploy
  
  after_success:
  - bash ./upload.sh
